security:
    encoders:
        Diff\UserBundle\Entity\User: 
            algorithm:        plaintext
            encode_as_base64: false
            

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         user_db:
            entity: { class: Diff\UserBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern:    /.*
            form_login:  
                check_path: /login_check
                login_path: /login
                provider: user_db	
            logout:     true
            anonymous: ~

        login:
            pattern:  login
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/order, roles: ROLE_USER }
        - { path: ^/trip, roles: ROLE_USER }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }