Diff\OrderTripBundle\Entity\Declaratie:
    type: entity
    table: declaratie
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tripid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        code:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: Name
        date:
            type: date
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
